/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tcs.tallerListas;

import com.tcs.tallerListas.beans.Estudiante;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Scanner;
import java.lang.Math;


public class IngresoEstudiantes {

	public static void main(String[] args) throws IOException {
            
                ArrayList<Estudiante> estudiantes = new ArrayList<Estudiante>();
                ArrayList<String> estudiantesRepetiran = new ArrayList<String>();
                Integer cantidadDeEstudiantes = 0, estudiantesEntre6y10años=0;
                ArrayList<Estudiante> jardin = new ArrayList<Estudiante>();
                ArrayList<Estudiante> primero = new ArrayList<Estudiante>();
                ArrayList<Estudiante> segundo = new ArrayList<Estudiante>();
                ArrayList<Estudiante> tercero = new ArrayList<Estudiante>();
                ArrayList<Estudiante> cuarto = new ArrayList<Estudiante>();
                ArrayList<Estudiante> quinto = new ArrayList<Estudiante>();


		System.out.println("################ Ingreso de estudiantes ################");
		
		try {
			Scanner data = new Scanner(new File("src/main/resources/data.txt"));
			
			while (data.hasNextLine()) {
				String[] estData = data.nextLine().split(",");
                                
                                //agrega los datos del estudiante al objeto
                                Estudiante estudiante = new Estudiante();
                                estudiante.setIdentificacion(estData[0]);
                                estudiante.setNombre(estData[1]);
                                estudiante.setEdad(Integer.parseInt(estData[2]));
                                estudiante.setGradoACursar(estData[3]);
                                estudiantes.add(estudiante);
                                
                                //aumenta contador de estudiantes
                                cantidadDeEstudiantes++;
                                
                                //contar estudiantes entre 6 y 10 años
                                if(estudiante.getEdad()>=6 && estudiante.getEdad()<=10){
                                    estudiantesEntre6y10años++;
                                }
                                
                                switch(estudiante.getGradoACursar()){
                                    case "Jardin":{
                                        jardin.add(estudiante);
                                        break;
                                    }
                                    case "Primero":{
                                        primero.add(estudiante);
                                        break;
                                    }
                                    case "Segundo":{
                                        segundo.add(estudiante);
                                        break;
                                    }
                                    case "Tercero":{
                                        tercero.add(estudiante);
                                        break;
                                    }
                                    case "Cuarto":{
                                        cuarto.add(estudiante);
                                        break;
                                    }
                                    case "Quinto":{
                                        quinto.add(estudiante);
                                        break;
                                    }
                                }
                                
			}
                        
                        //Imprimir información en consola
                        
                        //a. Número total de estudiantes registrados en el archivo
                        System.out.println("El número de estudiantes en el archivo es de "+cantidadDeEstudiantes);
                        System.out.println("");
                        //b. El número de estudiantes entre los 6 y 10 años de edad 
                        System.out.println("El número de estudiantes entre los 6 y 10 años de edad es de "+estudiantesEntre6y10años);
                        System.out.println("");
                        //c. Separar los estudiantes en diferentes listas por grado e imprimir
                        System.out.println("Estudiantes por grado");
                        System.out.println("");
                        System.out.println("JARDIN");
                        for (int i =0 ;i < jardin.size(); i++){
                            System.out.println("Identificación: "+jardin.get(i).getIdentificacion()+", Nombre: "+jardin.get(i).getNombre()+", Edad:"+jardin.get(i).getEdad());
                        }
                        System.out.println("");
                        System.out.println("PRIMERO");
                        for (int i =0 ;i < primero.size(); i++){
                            System.out.println("Identificación: "+primero.get(i).getIdentificacion()+", Nombre: "+primero.get(i).getNombre()+", Edad:"+primero.get(i).getEdad());
                        }
                        System.out.println("");
                        System.out.println("SEGUNDO");
                        for (int i =0 ;i < segundo.size(); i++){
                            System.out.println("Identificación: "+segundo.get(i).getIdentificacion()+", Nombre: "+segundo.get(i).getNombre()+", Edad:"+segundo.get(i).getEdad());
                        }
                        System.out.println("");
                        System.out.println("TERCERO");
                        for (int i =0 ;i < tercero.size(); i++){
                            System.out.println("Identificación: "+tercero.get(i).getIdentificacion()+", Nombre: "+tercero.get(i).getNombre()+", Edad:"+tercero.get(i).getEdad());
                        }
                        System.out.println("");
                        System.out.println("CUARTO");
                        for (int i =0 ;i < cuarto.size(); i++){
                            System.out.println("Identificación: "+cuarto.get(i).getIdentificacion()+", Nombre: "+cuarto.get(i).getNombre()+", Edad:"+cuarto.get(i).getEdad());
                        }
                        System.out.println("");
                        System.out.println("QUINTO");
                        for (int i =0 ;i < quinto.size(); i++){
                            System.out.println("Identificación: "+quinto.get(i).getIdentificacion()+", Nombre: "+quinto.get(i).getNombre()+", Edad:"+quinto.get(i).getEdad());
                        }
                        System.out.println("");
                        
                        //d. Si la identificación del estudiante empieza con “TI”, imprimir edad y grado.
                        System.out.println("Estudiantes cuya identificación empieza con TI");

                        for (int i =0 ;i < estudiantes.size(); i++){
                            if(estudiantes.get(i).getIdentificacion().substring(0, 2).equals("TI")){
                                System.out.println("Edad:"+estudiantes.get(i).getEdad()+" Grado a cursar: "+estudiantes.get(i).getGradoACursar());
                            }
                        }
                        System.out.println("");
                        
                        //4. Se deberá agregar un campo, luego de la edad, al archivo data.txt que indique si el estudiante repetirá el grado o no.
                        Writer dataWr;
                        try {
                            dataWr = new FileWriter("src/main/resources/data.txt");
                            for (int i =0 ;i < estudiantes.size(); i++){
                                Estudiante est = estudiantes.get(i);
                                String linea;
                                double valorAleatorio = Math.random()*(10)+1;
                                if(valorAleatorio>5){
                                    linea = String.join(",", est.getIdentificacion(),est.getNombre(),est.getEdad().toString(),"Debe Repetir",est.getGradoACursar());
                                    estudiantesRepetiran.add(est.getNombre());
                                }
                                else{                                    
                                    linea = String.join(",", est.getIdentificacion(),est.getNombre(),est.getEdad().toString(),"No debe repetir",est.getGradoACursar());
                                }
                                dataWr.write(linea+ "\r\n");
                            }
                            dataWr.flush();
                            dataWr.close();
                        } catch (FileNotFoundException e) {
                            System.out.println("El archivo src/main/resources/data.txt no se encuentra en la ruta especificada");
                        }
                        
                        //5. Estudiantes que repetirán el grado
                        System.out.println("Estudiantes que repetirán el grado");
                        for(int i =0 ;i <estudiantesRepetiran.size();i++){
                            System.out.println(estudiantesRepetiran.get(i));
                        }      
                        
		}catch (FileNotFoundException e) {
                    System.out.println("El archivo src/main/resources/data.txt no se encuentra en la ruta especificada");
		}catch (NumberFormatException e){
                    System.out.println("La edad no se pudo convertir de String a Entero");
                }
                
	}
}
